### ISSUE TITLE
Review of column name / field names

### ISSUE THREAD

**Issue by mskyttner** [mskyttner/swedishbirdrecoveries#1]
The field names used need to be corrected and each field name needs a description in the package.

The list of field names are here: https://github.com/mskyttner/swedishbirdrecoveries/blob/master/data-raw/get_test_data.R

**Comment by mskyttner** [comment]
These are the current field names:

name_swe, name_eng, sciname,
ringing_sex_code, ringing_sex_swe, ringing_sex_eng,
ringing_age_code, ringing_age_swe, ringing_age_eng,
ringing_date,
ringing_lat, ringing_lon,
ringing_country_swe, ringing_country_eng,
ringing_province_swe, ringing_province_eng,
ringing_majorregion, ringing_minorregion,
ringing_accu2,
recovery_date, recovery_accu_code, recovery_accu_swe, recovery_accu_eng, recovery_lat, recovery_lon,
recovery_accu2,
recovery_country_swe, recovery_country_eng,
recovery_province_swe, recovery_province_eng,
recovery_majorregion, recovery_minorregion,
distance, direction, days, hours,
recovery_code, recovery_det_swe, recovery_det_eng

**Comment by thomwenn** [comment]
Suggested new column names (and explanations): 
 name_swe,
 name_eng,
 sciname,
 ringing_sex_code,  (short code for selection, selecting the probable code N selects N and M)
 ringing_sex_swe,
 ringing_sex_eng,
 ringing_age_code,  (short code for selection, e.g. selecting 2+ will select all codes 20, 2+, 30, 3+ etc)
 ringing_age_swe,
 ringing_age_eng,
 ringing_date,
 ringing_lat,
 ringing_lon,
 ringing_country_swe,
 ringing_country_eng,
 ringing_province_swe,
 ringing_province_eng,
 ringing_majorplace,  _renamed_ 
 ringing_minorplace,  _renamed_  (more precise place name)
 recovery_type,  _renamed_  (alive, dead and some other cases)
 recovery_date,
 recovery_timeaccu_code,  _renamed_ 
 recovery_timeaccu_swe,  _renamed_ 
 recovery_timeaccu_eng,  _renamed_ 
 recovery_lat,
 recovery_lon,
 recovery_coord_accu,  _renamed_ 
 recovery_country_swe,
 recovery_country_eng,
 recovery_province_swe,
 recovery_province_eng,
 recovery_majorplace,  _renamed_ 
 recovery_minorplace,  _renamed_  (more precise place name)
 distance,  (km)
 direction,  (degrees - 360)
 days,
 hours,  (only up to 72, not added to days)
 recovery_code,  (four digit codes - long list of details)
 recovery_det_swe,
 recovery_det_eng

Hope this is clear enough

**Comment by mskyttner** [comment]
Fixed in aa12e3a68433420a3122e15b7cfb043b1bb103e9
