### ISSUE TITLE
Add UI filters

### ISSUE THREAD

**Issue by mskyttner** [mskyttner/swedishbirdrecoveries#10]
Add UI filters for lat, lon and time

**Comment by mskyttner** [comment]
Also the language switching needs to be there

**Comment by mskyttner** [comment]
These filters have been added back into the simplified UI.

**Comment by thomwenn** [comment]
Thanks. Should also make it possible to scroll the filters with mouse. Now they close as soon you click.

**Comment by mskyttner** [comment]
We have found issues with MSIE v 11 and selectize.js losing focus on click, more details here:

https://github.com/selectize/selectize.js/issues/1285

**Comment by mskyttner** [comment]
Fixed in production version now.
