### ISSUE TITLE
Issue with map background tiles not displaying

### ISSUE THREAD

**Issue by mskyttner** [mskyttner/swedishbirdrecoveries#18]
https://birdringing.bioatlas.se/ displays data on a gray background, not displaying map tiles properly.

The javascript console in the browser reports:

`Loading mixed (insecure) display content “http://a.tiles.wmflabs.org/bw-mapnik/3/0/3.png”`

It seems that the tile server that serves up the background map images is not working properly and needs to be switched. It looks so when attempting to load the background tile at http://c.tiles.wmflabs.org/bw-mapnik/3/0/2.png which gives a 404 response.

This is confirmed by running the code at https://gis.stackexchange.com/questions/56854/how-do-i-add-my-own-map-layers-to-leaflet - this used to work but doesn't any longer:

```r
library(leaflet)
 leaflet() %>% 
   addTiles(urlTemplate = "http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png", attribution = '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>') %>% 
   setView(-73.97125, 40.78306, zoom=10) 
```

**Comment by mskyttner** [comment]
@thomwenn - a redeploy has been made using another tile provider and it seems to work, please confirm that you see the same at https://birdringing.bioatlas.se/

**Comment by thomwenn** [comment]
Fine - it seems to work OK. Thanks!
