### ISSUE TITLE
Add "About tab"

### ISSUE THREAD

**Issue by mskyttner** [mskyttner/swedishbirdrecoveries#5]
Add a tab with Instructions, help text and contact details

**Comment by mskyttner** [comment]
A simple English and Swedish About page has been added with some basic stats and a logo.

**Comment by thomwenn** [comment]
This is fine! We can write explanatory texts in both languages to make it more user friendly. Also informing why some endangered species are not included in the dataset.

**Comment by mskyttner** [comment]
Fixed in production version now.
