### ISSUE TITLE
Automatic nightly dataset updates

### ISSUE THREAD

**Issue by mskyttner** [mskyttner/swedishbirdrecoveries#7]
Ensure production deployment dataset is updated nightly.

**Comment by mskyttner** [comment]
A script has been added to do this, but in the production environment, some DNS settings seems to prevent reaching out to the source dataset location, and this needs investigation and fixing.

**Comment by thomwenn** [comment]
Critical fact, but as I understood it is solved already. Although not implemented.

**Comment by mskyttner** [comment]
Fixed in production version now.
